apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi  # Adjust size as needed
  storageClassName: gp2  # StorageClass name

